### ISSUE TITLE
Problems with setting up Pypiper + Pipelines

### ISSUE THREAD

**Issue by nfortelny** [epigen/pypiper#17]
First: thank you all for developing all of this. It's very handy

I just went through the whole process of making it run on my system and was asked to summarize my experience. It was a bit tricky to find the right versions that fit together plus correct some bugs. In particular, NGSTK and Pipelines (or open_pipelines) didn’t work together, neither master – master nor dev – dev.  It's running for me at the moment and there ultimately weren't that many things to fix (but they were tricky to find). What I think would help most is to know which versions go together. Here are a few specific points, I will submit them in the dev branches (which I ultimately used):
- NGSTK (master) was missing one method entirely (added in the dev branch)
- In the dev and master branch, the “all_args” argument in pypiper.add_pypiper_args(parser, all_args=True) was set in all pipelines. However pypiper didn’t use this argument. (I had to use ‘groups=[“all”]’)
- NGSTK bam_fastq was missing the “+” in cmd += r'{ print "@"$1"\n"$10"\n+\n"$11
- I needed the pipelines’ yaml files that are found in dev branch
- Looper wasn’t in $PATH upon installation, for some reason it worked in the microtest but it took me some time to figure out where pip had installed it to add it to $PATH to make it work outside the virtual env

Some ideas on how we could do things in the future:
- All pipelines should be tested before a release because specific pipelines require specific ngstk/pypiper methods thus testing only some pipelines does not guarantee full functionality of ngstk/pypiper
- For the current state of things, I would say develop the dev branch to work, then merge with master for all repos. In general, I would suggest using dev branch to fix things and other branches to implement yet additional functionality, thus keeping those two things separate
- Some of the errors above are found by running “python YOUR_PIPELINE.py” we could use this for tests?

Thoughts?

Nik

**Comment by nfortelny** [comment]
- I ran across a few other things, here for completeness' sake:
- I needed to install pipelines (pip install --user --upgrade PathToPipelines)
- The definition of required tools for pipelines in the .yaml files is useful but some things are not captured:
1. The BitSeq pipelines required the R-package "BitSeq"
2. The bam2wig script needed the qcmodule (I think in the TopHat pipeline)
3. samtools is used by ngstk and maybe also some pipelines (at least it's defined in the yamls) some pipelines require specific versions of samtools and others not. This does make a difference in syntax and throws errors. I'm wondering if it's not best to move all samtools calls (or actually generation of the bash commands) to ngstk / pypiper

**Comment by cdietzgit** [comment]
This looks like a very comprehensive and useful feedback. Thanks for that. We should definitely work on bunch of the mentioned points.

* For the NGSTK bam_to_fastq I rolled back to the old function until the new one get fixed, see caad85e0ced561ca67f780ad947c875477a3ed10
* For samtools version, we could indeed agree to all converge into using the latest version available on the cluster which is 1.3 or 1.3.1
* What about having one or two persons explicitly responsible for each pipeline, they would be in charge of the maintenance and upgrading their pipelines as soon as a new release of looper/pypiper is pushed
* For each release of looper/pypiper could we use Tags, would make it easier to refer to a specific version of the code (for ourselves and for publications)

**Comment by nsheff** [comment]
Can we make a push in the next couple of weeks to merge dev into master and solve this issue?

Then we can define a first major release and it will be at least a stable point from which to build.

A few comments to your points:

I think it's unrealistic to test all pipelines before a release centrally, though, since ideally there will be many pipelines from many authors; at some point the burden is shifted to them to update, but hopefully this is not a huge burden because as things stabilize, we will not introduce any backwards-incompatible changes. But authors (or maintainers) of pipelines can do so, as suggested by @cdietzgit  -- but again, hopefully this becomes minimal as we will keep things backwards compatible when we hit the critical utility point soon, if not already.

**Comment by afrendeiro** [comment]
Yeess! I can dedicate time to this but mostly next week.

**Comment by nfortelny** [comment]
I think that's a good plan!

**Comment by nsheff** [comment]
@nfortelny Does the `0.4` release solve these issues? I will close this issue; feel free to re-open if you are still having problems.

From now on releases will be more systematic, updates will all happen on dev or feature branches, and the master version will always have the latest stable version.
