### ISSUE TITLE
Enable full pipelinemanager-free usage of NGSTk

### ISSUE THREAD

**Issue by afrendeiro** [epigen/pypiper#18]
(dev branch)
Right now, if not passing a pipeline manager object to NGSTk (`pm`) one could not many commands, since these call the `tools` attributes of the NGSTk `self`, resulting in error.

Example:

``` python
from pypiper import NGSTk
tk = NGSTk()
tk.fastqc("a", "a")
```

> AttributeError: 'str' object has no attribute 'fastqc'

This is because the fastqc command calls internally "self.tools.fastqc" and since tools does not exist (it comes from the pipeline manager) it is returning a string "tools" which has no attribute "fastqc".

We should enable all commands in NGSTk to be run even if not passing a `pm` object to it initially.

**Comment by afrendeiro** [comment]
My commit adds a "tools" and "parameters" variables to the NGSTk class when a pipeline manager (`pm`) object is not passed, which are empty `AttributeDict` objects.

This allows:
```python
from pypiper import NGSTk
tk = NGSTk()
tk.fastqc("a", "a")
```
> 'fastqc --noextract --outdir a a'

because now "tools" is an `AttributeDict` returning the identity of the requested attribute.
This is only done when a `pm` object is not passed, it should the usage of a `pm`. Let me know otherwise.
If no complains, I'll close this in a few days.

**Comment by cdietzgit** [comment]
This can only be a good feature. Thanks for implementing this.

**Comment by nsheff** [comment]
NGTSk was originally pipelinemanager-free. I added the link so that ngstk could use some stuff from the PM, which is really useful sometimes.

When would someone want an NGSTk without a PM?

But this is fine with me anyway... I think the solution is great, just setting a better default. But, it's just hard-coding tools and parameters and we should instead think of a universal solution if possible.

**Comment by afrendeiro** [comment]
Any more ideas? Is this solved?

**Comment by nsheff** [comment]
Ok, fine with me;

But this use case you're describing is really outside the pypiper/looper framework and seems more like it should be a separate thing, doesn't it? For instance, I don't think we should be hard-coding slurm bindings; this is accomplished through the more flexible templating system.

**Comment by nsheff** [comment]
As I think more about this, I think this is more like an exploratory analysis; maybe we should think a bit about how to adapt to making exploratory analysis more straightforward.
