### ISSUE TITLE
bugs in chipseq.py & ngstk.py

### ISSUE THREAD

**Issue by mtugrul** [epigen/pypiper#36]
Peak calling in open_pipelines/chipseq.py was not working. It turns out that there are a couple of issues to be corrected. Here are my solutions.

1-) In open_pipelines/chipseq.py (line 535), an underscore is missing, i.e.  pipe_manager.wait_for_file... -> pipe_manager._wait_for_file... 
2-) macs2CallPeaks in pypiper/ngstk.py (line 1140) was not functioning properly when it is called in open_pipelines/chipseq.py (line 545). I think this is due to not including "self" in macs2CallPeaks's definition. (this subtle problem is explained here: http://blog.rtwilson.com/got-multiple-values-for-argument-error-with-keyword-arguments-in-python-classes/)). I added a "self" in my local copy.
3-) Also, to be consistent with open_pipelines/chipseq.py, I also changed treatmentBam**s** -> treatmentBam AND controlBam**s** -> controlBam in macs2CallPeaks in pypiper/ngstk.py (line 1140)

With these 3 changes, now open_pipelines/chipseq.py call peaks properly.

**Comment by nsheff** [comment]
@afrendeiro  did your commit solve this issue?

**Comment by afrendeiro** [comment]
Yes, sorry it was solved here https://github.com/epigen/open_pipelines/issues/1
