### ISSUE TITLE
Dynamic recovery

### ISSUE THREAD

**Issue by nsheff** [epigen/pypiper#37]
Originally prompted by an issue in `looper` by @rcorces: epigen/looper#140

> Solution: we could have a new mode called 'dynamic recover' mode. This runs in normal mode by default, but if a 'recover' flag is set, THEN it runs in recover mode. In other words, if a file lock is set, it checks for a recover flag, and then restarts only if a recover flag exists. If a dynamic recover job is pre-empted (ie it fails via a sigkill or a sigterm, not via a job failure), then it sets a recover flag. When a pre-empted job is restarted, it will recover; when a job that failed naturally is restarted, it will not. A dual-submission still succeeds.

> Wow that's pretty sweet. On Sherlock (or any cluster that can pre-empt jobs) you would just always run in dynamic recover mode. Thoughts? This would be pretty easy to implement actually, and would fit sherlock's system perfectly. everything would be handled automatically.

**Comment by rcorces** [comment]
This would be awesome.

**Comment by nsheff** [comment]
It should work now, give it a try.
