### ISSUE TITLE
Dynamic recovery not working on preempted jobs

### ISSUE THREAD

**Issue by rcorces** [epigen/pypiper#40]
I havent been able to figure this one out.

Running pypiper-0.5.0rc2 and looper 0.6.0rc1

I ran 37 jobs. 10 completed without problem and ran through the whole pipeline perfectly. The remaining 27 all ran into problems during the pre-alignments stage, failing to complete either the alphasat or alu alignments. They all generated the tmp intermediate bam files but did not compile them into the final bam file.

The one thing that all of the failed jobs have in common is that they were preempted. All of the completed jobs were not preempted. It looks like the jobs have some trouble recovering after being re-submitted. I'm attaching an example log file here. It looks like there is some confusion about the file lock during alignment. It looks like the alignment is not restarted but rather the pipeline just waits for it to finish (and the file lock to be released) and it never does.

Happy to help trouble shoot this. I dont have much intuition for how this is all happnning. I'll keep digging.

**Comment by nsheff** [comment]
Ok, the dynamic recover must be failing.
Can you look and see if there is any file in that folder named "lock.recover*"

I think it might be:
`/oak/stanford/groups/howchang/users/mcorces/TCGA_ATAC/alignments/170614_TCGA_A602/results_pipeline/BRCA-1B6783CB-7D24-4D13-908A-19CCAD4CFF34-170523-A602-006-B1-T1/lock.recover.prealignments__BRCA-1B6783CB-7D24-4D13-908A-19CCAD4CFF34-170523-A602-006-B1-T1_human_alu.bam`

**Comment by nsheff** [comment]
actually I think I see what's happening. Can you look at the slurm logs instead of the pypiper logs to see what slurm is doing?

**Comment by nsheff** [comment]
if you look at the log right here, it says `<pre>` and then it just restarts:
```
... results_pipeline/BRCA-1B6783CB-7D24-4D13-908A-19CCAD4CFF34-170523-A602-006-B1-T1/prealignments/BRCA-1B6783CB-7D24-4D13-908A-19CCAD4CFF34-170523-A602-006-B1-T1_unmap_human_alu_R%.fq.gz | samtools view -bS - -@ 1 | samtools sort - -@ 1 -o /oak/stanford/groups/howchang/users/mcorces/TCGA_ATAC/alignments/170614_TCGA_A602/results_pipeline/BRCA-1B6783CB-7D24-4D13-908A-19CCAD4CFF34-170523-A602-006-B1-T1/prealignments/BRCA-1B6783CB-7D24-4D13-908A-19CCAD4CFF34-170523-A602-006-B1-T1_human_alu.bam > /oak/stanford/groups/howchang/users/mcorces/TCGA_ATAC/alignments/170614_TCGA_A602/results_pipeline/BRCA-1B6783CB-7D24-4D13-908A-19CCAD4CFF34-170523-A602-006-B1-T1/prealignments/BRCA-1B6783CB-7D24-4D13-908A-19CCAD4CFF34-170523-A602-006-B1-T1_human_alu.bam`

<pre>
----------------------------------------
##### [Pipeline run code and environment:]
*              Command: `/share/PI/howchang/users/mcorces/tools/pipelines/ATACseq-dev/pipelines/ATACseq.py --input2 /oak/stanford/groups/howchang/users/mcorces/TCGA_ATAC/alignments/170614_TCGA_A602/fastq/BRCA-1B6783CB-7D24-4D13-908A-19CCAD4CFF34-170523-A602-006-B1-T1-GTATTCGG-CTTAATGC_S3_L001_R2_001.fastq.gz --genome hg38 --single-or-paired paired --sample-name BRCA-1B6783CB-7D24-4D13-908A-19CCAD4CFF34-170523-A602-006-B1-T1 --input /oak/stanford/groups/howchang/users/mcorces/TCGA_ATAC/alignments/170614_TCGA_A602/fastq/BRCA-1B6783CB-7D24-4D13-908A-19CCAD4CFF34-170523-A602-006-B
```


this means pypiper is never getting a SIGTERM or SIGTERM. Try it yourself pressing Ctrl + C. Slurm may not send a SIGTERM or SIGINT, but go straight to SIGKILL, which would not give python a chance to accept the signal and shut itself down and set the recover flag. 

Everything is working from my end -- it must be that when slurm is pre-empting, it's just sending SIGKILL and not SIGTERM. That's not very nice of them. What it should do is send a nice kill signal to let the process shut itself down. give it a few seconds. if it doesn't respond, then kill it. that's what a proper slurm config is supposed to do and that's what I'm relying on.

Is it possible that sherlock is not doing it this way? Essentially, slurm needs to play nice for this to work.

The alternative is, if you take responsibility for making sure 2 pipelines aren't writing the same file at the same time (which should be the case in many pipelines, unless you submit the same sample twice), then you can sacrifice this safety control and get it to still work *in spite of* a slurm misconfiguration by running everything in recover mode (`-R`).

I don't think there's any better way to do this... The right answer is just that slurm needs to be reconfigured I think.

Or am I missing something?

**Comment by rcorces** [comment]
there is a file named "lock.prealignments" but not "lock.recover"
![image](https://user-images.githubusercontent.com/10343046/28285369-51fbc99c-6ae9-11e7-8f58-ead943efc9db.png)

**Comment by nsheff** [comment]
Yep. The recover file is set in the SIGINT/SIGTERM handler. So the SIGINT/SIGTERM is never begin given to python.

I maintain that slurm is NOT passing a SIGTERM signal while preempting despite what sysadmins may believe. Maybe worth asking them to check in more detail.

**Comment by nsheff** [comment]
in the meantime, like I said earlier, you can get these jobs to run through by adding `-R` to your looper command, which will pass along to the pipeline runs and tell them to force recovery mode.

**Comment by nsheff** [comment]
actually could you check 1 more thing? Is there any `lock.recover.` file in the `prealignments` subfolder?

**Comment by rcorces** [comment]
nope. no lock.recover files anywhere in any of the folders

On Mon, Jul 17, 2017 at 12:23 PM, Nathan Sheffield <notifications@github.com

**Comment by vreuter** [comment]
It seems like this one's been solved, or is it still active?

**Comment by rcorces** [comment]
I dont seem to be having this issue any more. I think it could be closed

**Comment by vreuter** [comment]
OK great I'll close for now but reopen if this rears up.
