### ISSUE TITLE
macs2CallPeaks not producing NAME_model.r script

### ISSUE THREAD

**Issue by vreuter** [epigen/pypiper#46]
From the NGSTK code and from the MACS 2 docs, it looks like the model building intends to write a script called `NAME_model.r`, where `NAME` is the sample name. When this function's called from `chipseq.py` in `open_pipelines`, though, that script is missing, causing the subsequent plotting call to fail. I thought maybe the name was off, but there's actually no `.r` file in the any of the project's sample's output folder. I'm just wondering if anyone else has run into this and perhaps knows what could be happening, maybe @afrendeiro ? There's no indication in the sample's logfile:
```
Calling peaks with MACS2 (08-22 00:19:55) elapsed:0:00:00 _TIME_

Target exists: `/sfs/lustre/allocations/shefflab/processed//kipnis_chip/full/results_pipeline/chip_30k/peaks/chip_30k_peaks.broadPeak`
> `peaks`       1911319 chipseq _RES_
Ploting MACS2 model (08-22 00:19:56) elapsed:0:00:01 _TIME_

Target to produce: `/sfs/lustre/allocations/shefflab/processed//kipnis_chip/full/results_pipeline/chip_30k/peaks/chip_30k/chip_30k_model.pdf`
> `Rscript /sfs/lustre/allocations/shefflab/processed/kipnis_chip/full/results_pipeline/chip_30k_model.r`

<pre>
Fatal error: cannot open file '/sfs/lustre/allocations/shefflab/processed/kipnis_chip/full/results_pipeline/chip_30k_model.r': No such file or directory
</pre>
```

**Comment by vreuter** [comment]
Ah maybe `--nomodel` to MACS2? It looks like that's happening when `broad=True` is passed to `macs2CallPeaks` in NGSTK.

**Comment by afrendeiro** [comment]
Good catch.
The parameters for broad factor peak calling with MACS2 bypass model creation (`--nomodel` option) and therefore no model file is created.
This is therefore a pipeline fault as it should check for this before trying to plot the MACS2 model.

Fixed here https://github.com/epigen/open_pipelines/commit/f2107aa3f11d92abbaefd8c08684994e20895daa
