### ISSUE TITLE
NGSTk function name/argument homogeneization

### ISSUE THREAD

**Issue by afrendeiro** [epigen/pypiper#50]
Since many of the NGSTk functions were written long ago, they aren't all using the same naming scheme (eg. camel caps vs lowercase with underscores).
This would mean updating all code that uses these functions (mostly pipelines I guess).

**Comment by nsheff** [comment]
Yeah just go ahead and do this on the dev branch. I already changed tabs to spaces ...

I released 0.6 just now so we'd have a stable, up-to-date base, but let's go to town on these things to revamp for 0.7, it's fine with me.

**Comment by afrendeiro** [comment]
Alright. If you guys have code using some of this functions you'll might want to update it too.
I'll switch the pipelines to spaces too then.

**Comment by nsheff** [comment]
Yeah. Do it. We'll adapt anything it breaks on the pipeline side.

**Comment by afrendeiro** [comment]
Okay. 
I might be able to write docstrings for these functions too sometime near.
