### ISSUE TITLE
error with tee output

### ISSUE THREAD

**Issue by nsheff** [epigen/pypiper#60]
when doing a local compute run, I get this error

```
Pypiper terminating spawned child process 221622...
child process terminated
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```

having trouble figuring out where it's coming from.

**Comment by vreuter** [comment]
Is this master, dev, or my fork’s checkpoint branch?

**Comment by nsheff** [comment]
let's see... output says `0.6.0` so I believe it's master...

**Comment by nsheff** [comment]
just checked -- same behavior in `0.7.0-dev` from `vreuter:checkpoint`

**Comment by vreuter** [comment]
OK just wanted to make sure I hadn't introduced this one. Too bad an incidental fix wasn't already a passenger with that branch's changes.

**Comment by vreuter** [comment]
https://bugs.python.org/issue11380

**Comment by nsheff** [comment]
that bug is from 2012 though and this is a recent change...

**Comment by vreuter** [comment]
What’s a recent change? You said it occurred in 0.6

**Comment by nsheff** [comment]
Recent means after 2012 :)

**Comment by nsheff** [comment]
I believe it may have something to do with all the fallout from the rivanna upgrade, so let's just ignore it for now.

**Comment by nsheff** [comment]
appears to have been a local isolated incident relative to our cluster upgrade that is no longer manifest.
